# Generated by Django 2.1.1 on 2018-09-13 02:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20180910_0923'),
        ('shop', '0002_auto_20180912_0310'),
    ]

    operations = [
    ]
